#!/bin/bash
W=$(echo "$WATER" | tr "water" "01234")
S=$(echo "$STIR" | tr "stir." "01234")
W=$(echo "ibase=5;$W" | bc)
S=$(echo "ibase=5;$S" | bc)
N=$((W + S))
R=$(echo "obase=8;$N" | bc)
echo "$R" | tr "01234567" "bestchol"
